### ISSUE TITLE
Homebridge fails to load with the latest betas

### ISSUE THREAD

**Issue by kavehv** [pradeepmouli/homebridge-isy-js#20]
Updated homebridge today (along with this plugin) and now it fails to load:

`
2020-4-2#19:54:9- Device: ZW 002 Repeater type: 4.15.1.0 is not specifically supported, returning generic device object.
2020-4-2#19:54:9- Device: ZW 002 Multilevel Switch type: 4.15.1.0 is not specifically supported, returning generic device object.
2020-4-2#19:54:9- Device: ZW 002 Color Switch type: 4.15.1.0 is not specifically supported, returning generic device object.
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- GARAGE: Garage Door Initial set during startup the sensor is closed so defaulting states to closed
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Ignoring device: Garage Door Relay [22 D5 62 2] because of rule [] [] [22 D5 62 2]
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Ignoring device: Living Room Patio-Closed [31 BC FE 2] because of rule [-Closed] [] []
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Ignoring device: Kitchen Patio-Closed [31 C1 29 2] because of rule [-Closed] [] []
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Ignoring device: Living Room Patio-Heartbeat [31 BC FE 4] because of rule [-Heartbeat] [] []
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Ignoring device: Kitchen Patio-Heartbeat [31 C1 29 4] because of rule [-Heartbeat] [] []
[37m[5/26/2020, 7:54:09 PM] [39m[36m[isy-js] [39m120-4-2#19:54:9- ISYPLATFORM: Filtered device has: 22 devices
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Living Room Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Backyard Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Living Room (Hallway Switch)'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Living Room (Garage Switch)'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Backyard Lights (Hallway Swit'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Garage Door'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Garage Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Entry Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Can Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Dining Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Pendant Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Under Cabinet Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Light Control'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Hallway Lights'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Living Room Patio-Opened'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Kitchen Patio-Opened'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Hallway Light'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Decorations'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Front Door'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Porch Light'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Entry Lights (Front Door)'...
[37m[5/26/2020, 7:54:09 PM] [39mInitializing platform accessory 'Study Lights'...
[37m[5/26/2020, 7:54:09 PM] [39m[31mError: Did not bind any sockets![39m
[31m at new MDNSServer (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:98:13)[39m
[31m at new Responder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:47:19)[39m
[31m at Object.createResponder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/index.ts:34:10)[39m
[31m at new Advertiser (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Advertiser.ts:66:22)[39m
[31m at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:966:24)[39m
[31m at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:191:17)[39m
[31m at /usr/local/lib/node_modules/homebridge/src/server.ts:163:24[39m
[31m at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[31m at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:5)[39m
[37m[5/26/2020, 7:54:09 PM] [39mGot SIGTERM, shutting down Homebridge...
[37m[5/26/2020, 7:54:14 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[5/26/2020, 7:54:19 PM][0m [36m[HB Supervisor][0m Restarting Homebridge...
[37m[5/26/2020, 7:54:19 PM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -P /homebridge/node_modules
[37m[5/26/2020, 7:54:20 PM][0m [36m[HB Supervisor][0m Started Homebridge v1.1.1-beta.3 with PID: 839
[37m[5/26/2020, 7:54:20 PM] [39mLoaded config.json with 0 accessories and 1 platforms.
[37m[5/26/2020, 7:54:20 PM] [39m---
[37m[5/26/2020, 7:54:20 PM] [39mLoaded plugin: homebridge-dummy@0.4.1
[37m[5/26/2020, 7:54:20 PM] [39mRegistering accessory 'homebridge-dummy.DummySwitch'
[37m[5/26/2020, 7:54:20 PM] [39m---
[37m[5/26/2020, 7:54:20 PM] [39mLoaded plugin: homebridge-isy@0.5.0-rc4
[37m[5/26/2020, 7:54:20 PM] [39mRegistering platform 'homebridge-isy.ISY'
[37m[5/26/2020, 7:54:20 PM] [39m---
[37m[5/26/2020, 7:54:20 PM] [39mLoaded plugin: homebridge-isy-js@0.1.9
[37m[5/26/2020, 7:54:20 PM] [39mRegistering platform 'homebridge-isy-js.isy-js'
[37m[5/26/2020, 7:54:20 PM] [39m---
[37m[5/26/2020, 7:54:20 PM] [39mLoaded plugin: homebridge-config-ui-x@4.20.0
[37m[5/26/2020, 7:54:20 PM] [39mRegistering platform 'homebridge-config-ui-x.config'
[37m[5/26/2020, 7:54:20 PM] [39m---
[37m[5/26/2020, 7:54:20 PM] [39mLoading 1 platforms...
[37m[5/26/2020, 7:54:20 PM] [39m[36m[isy-js] [39mInitializing isy-js platform...
2020-4-2#19:54:21- Device: ZW 002 Repeater type: 4.15.1.0 is not specifically supported, returning generic device object.
2020-4-2#19:54:21- Device: ZW 002 Multilevel Switch type: 4.15.1.0 is not specifically supported, returning generic device object.
2020-4-2#19:54:21- Device: ZW 002 Color Switch type: 4.15.1.0 is not specifically supported, returning generic device object.
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- GARAGE: Garage Door Initial set during startup the sensor is closed so defaulting states to closed
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Ignoring device: Garage Door Relay [22 D5 62 2] because of rule [] [] [22 D5 62 2]
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Ignoring device: Living Room Patio-Closed [31 BC FE 2] because of rule [-Closed] [] []
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Ignoring device: Kitchen Patio-Closed [31 C1 29 2] because of rule [-Closed] [] []
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Ignoring device: Living Room Patio-Heartbeat [31 BC FE 4] because of rule [-Heartbeat] [] []
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Ignoring device: Kitchen Patio-Heartbeat [31 C1 29 4] because of rule [-Heartbeat] [] []
[37m[5/26/2020, 7:54:21 PM] [39m[36m[isy-js] [39m120-4-2#19:54:21- ISYPLATFORM: Filtered device has: 22 devices
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Living Room Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Backyard Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Living Room (Hallway Switch)'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Living Room (Garage Switch)'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Backyard Lights (Hallway Swit'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Garage Door'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Garage Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Entry Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Can Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Dining Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Pendant Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Under Cabinet Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Light Control'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Hallway Lights'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Living Room Patio-Opened'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Kitchen Patio-Opened'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Hallway Light'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Decorations'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Front Door'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Porch Light'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Entry Lights (Front Door)'...
[37m[5/26/2020, 7:54:21 PM] [39mInitializing platform accessory 'Study Lights'...
[37m[5/26/2020, 7:54:21 PM] [39m[31mError: Did not bind any sockets![39m
[31m at new MDNSServer (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:98:13)[39m
[31m at new Responder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:47:19)[39m
[31m at Object.createResponder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/index.ts:34:10)[39m
[31m at new Advertiser (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Advertiser.ts:66:22)[39m
[31m at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:966:24)[39m
[31m at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:191:17)[39m
[31m at /usr/local/lib/node_modules/homebridge/src/server.ts:163:24[39m
[31m at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[31m at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:5)[39m
[37m[5/26/2020, 7:54:21 PM] [39mGot SIGTERM, shutting down Homebridge...
`

**Comment by pradeepmouli** [comment]
Looks like this is homebridge-isy-js - not homebridge-isy.

**Comment by kavehv** [comment]
I see both.  Anyhow, reverting to Homebridge 1.1.0 (latest) seems to have made things work again.  Something seems broken between the latest betas and this plugin.
